### ISSUE TITLE
Option [nostandards] does not work as expected

### ISSUE THREAD

**Issue by tpellard** [natalieweber/leipzig#5]
The following document produces an error `Undefined control sequence \Nom` when the `nostandards` option is used.

```
\documentclass{article}
\usepackage[nostandards]{leipzig}
\makeglossaries
\begin{document}
Test \Nom
\printglosses
\end{document}
```

On the other hand, the following document compiles correctly but prints the standard abbreviations when using glossary commands, despite the `nostandards`option.
```
\documentclass{article}
\usepackage[nostandards]{leipzig}
\makeglossaries
\begin{document}
Test \acrshort{nom}
\printglosses
\end{document}
```

**Comment by natalieweber** [comment]
Odd. Thanks! Will have a look soon.

**Comment by natalieweber** [comment]
Was a typo; should be fixed now.
